In [2]:
import numpy as np

In [4]:
a = np.zeros((2,4))

In [6]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a.shape

(2, 4)

In [8]:
a.ndim

2

In [9]:
a.size

8

In [10]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.full((2,3,4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [12]:
np.empty((2,3, 9))

array([[[1.45067536e-311, 1.45068726e-311, 0.00000000e+000,
         6.95287745e-310, 2.32210854e-322, 1.45070174e-311,
         1.45070174e-311, 1.45070174e-311, 1.45070174e-311],
        [1.45070165e-311, 1.45070174e-311, 1.45070165e-311,
         1.45070165e-311, 1.45070174e-311, 1.45070165e-311,
         1.45070174e-311, 1.45070174e-311, 1.45070165e-311],
        [1.45070174e-311, 1.45070165e-311, 1.45070165e-311,
         1.45070174e-311, 1.45070174e-311, 1.45070165e-311,
         1.45070174e-311, 1.45070165e-311, 1.45070174e-311]],

       [[1.45070174e-311, 1.45070174e-311, 1.45070174e-311,
         1.45070174e-311, 1.45070165e-311, 1.45070174e-311,
         1.45070174e-311, 1.45070174e-311, 1.45070174e-311],
        [1.45070174e-311, 1.45070174e-311, 1.45070174e-311,
         1.45070174e-311, 1.45070165e-311, 1.45070165e-311,
         1.45070165e-311, 1.45070174e-311, 1.45070165e-311],
        [1.45070174e-311, 1.45070174e-311, 1.45070174e-311,
         1.45070174e-311, 1.45070